---
- name: Setting up a IIS Development Server
  hosts: windows
  gather_facts: yes
  vars:
    win_features:
      - "Web-Mgmt-Tools"  
      - "Web-Asp-Net45"
    local_users:
      - name: "iis_admin"
        description: "Break Glass Account for Administrators"
        groups: "Administrators" 
      - name: "iis_general_user"
        description: "General service account for IIS applications."
        groups: "Users" 
    logon_message_caption: "Welcome to Our Lab Environment"
    logon_message_text: |
      This server is part of the Ansible 101 Lab.
      Unauthorized access is strictly prohibited.
      All activities may be monitored.
      If you are not an authorized user, disconnect immediately.
  tasks:
    - name: Install IIS server utilities
      ansible.windows.win_feature:
        name: "{{ item }}"
        state: present
      loop: "{{ win_features }}"

    - name: Install required local service accounts
      ansible.windows.win_user:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ local_users }}"
      when: add_users
 
    - name: Set the Legal Notice Caption
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeCaption
        data: "{{ logon_message_caption }}"
        type: string 
        state: present 

    - name: Set the Legal Notice Text
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeText
        data: "{{ logon_message_text }}"
        type: string 
        state: present 

# ---
# - name: Installing IIS on a Windows Server
#   hosts: windows
#   gather_facts: yes
#   vars:
#     win_features:
#       - "Web-Mgmt-Tools"  
#       - "Web-Asp-Net45"
#     local_users:
#       - name: "iis_admin"
#         description: "Break Glass Account for Administrators"
#         groups: "Administrators" # Add to Administrators group for demo purposes
#       - name: "iis_general_user"
#         description: "General service account for IIS applications."
#         groups: "Users" # Add to Users group
#     logon_message_caption: "Welcome to Our Lab Environment"
#     logon_message_text: |
#       This server is part of the Ansible 101 Lab.
#       Unauthorized access is strictly prohibited.
#       All activities may be monitored.
#       If you are not an authorized user, disconnect immediately.

      
#   tasks:

#     - name: Install IIS server utilities
#       ansible.windows.win_feature:
#         name: "{{ item }}"
#         state: present
#       loop: "{{ win_features }}"

#     - name: Install required local service accounts
#       ansible.windows.win_user:
#         name: "{{ item.name }}"
#         description: "{{ item.description }}"
#         groups: "{{ item.groups }}"
#         state: present
#       loop: "{{ local_users }}"

#     - name: Set the Legal Notice Caption
#       # The win_regedit module is used to manage Windows Registry keys.

#       ansible.windows.win_regedit:
#         path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
#         name: LegalNoticeCaption
#         data: "{{ logon_message_caption }}"
#         type: string # Ensure the data type is string (REG_SZ)
#         state: present # Ensure the key-value pair exists

#     - name: Set the Legal Notice Text
#       ansible.windows.win_regedit:
#         path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
#         name: LegalNoticeText
#         data: "{{ logon_message_text }}"
#         type: string # Ensure the data type is string (REG_SZ)
#         state: present # Ensure the key-value pair exists


      

  